Repository GraduationDku/tastyHub, pull requests merged in 2024-06, with the labels that each got.

#69 Maps
  be/tastyhub/src/main/java/com/example/tastyhub/common/domain/naver/service/NaverService.java
  be/tastyhub/src/main/java/com/example/tastyhub/common/domain/user/controller/UserController.java
  be/tastyhub/src/main/java/com/example/tastyhub/common/domain/user/dtos/UserNameResponse.java
  be/tastyhub/src/main/java/com/example/tastyhub/common/domain/user/service/UserService.java
  be/tastyhub/src/main/java/com/example/tastyhub/common/domain/user/service/UserServiceImpl.java
  be/tastyhub/src/main/java/com/example/tastyhub/common/domain/village/dtos/LocationRequest.java
  be/tastyhub/src/main/java/com/example/tastyhub/common/domain/village/entity/Village.java
  be/tastyhub/src/main/java/com/example/tastyhub/common/domain/village/service/VillageServiceImpl.java
  be/tastyhub/src/test/java/com/example/tastyhub/common/domain/village/service/VillageServiceImplTest.java
Labels: enhancement

#71 Fix <(post)> : 게시글 조회 로직 조건 변경
  be/tastyhub/src/main/java/com/example/tastyhub/common/domain/post/repository/PostRepositoryQueryImpl.java
Labels: fix

#72 Review
  .github/workflows/DockerCD.yml
  be/tastyhub/src/main/java/com/example/tastyhub/common/config/APIConfig.java
  be/tastyhub/src/main/java/com/example/tastyhub/common/domain/like/controller/LikeController.java
  be/tastyhub/src/main/java/com/example/tastyhub/common/domain/like/entity/Like.java
  be/tastyhub/src/main/java/com/example/tastyhub/common/domain/like/repository/LikeRepository.java
  be/tastyhub/src/main/java/com/example/tastyhub/common/domain/like/service/LikeService.java
  be/tastyhub/src/main/java/com/example/tastyhub/common/domain/like/service/LikeServiceImpl.java
  be/tastyhub/src/main/java/com/example/tastyhub/common/domain/recipeReview/controller/RecipeReviewController.java
  be/tastyhub/src/main/java/com/example/tastyhub/common/domain/recipeReview/dtos/PagingRecipeReviewResponse.java
  be/tastyhub/src/main/java/com/example/tastyhub/common/domain/recipeReview/dtos/RecipeReviewCreateRequest.java
  be/tastyhub/src/main/java/com/example/tastyhub/common/domain/recipeReview/dtos/RecipeReviewUpdateRequest.java
  be/tastyhub/src/main/java/com/example/tastyhub/common/domain/recipeReview/entity/RecipeReview.java
  be/tastyhub/src/main/java/com/example/tastyhub/common/domain/recipeReview/repository/RecipeReviewRepository.java
  be/tastyhub/src/main/java/com/example/tastyhub/common/domain/recipeReview/repository/RecipeReviewRepositoryQuery.java
  be/tastyhub/src/main/java/com/example/tastyhub/common/domain/recipeReview/repository/RecipeReviewRepositoryQueryImpl.java
  be/tastyhub/src/main/java/com/example/tastyhub/common/domain/recipeReview/service/RecipeReviewService.java
  be/tastyhub/src/main/java/com/example/tastyhub/common/domain/recipeReview/service/RecipeReviewServiceImpl.java
  be/tastyhub/src/main/java/com/example/tastyhub/common/domain/userReview/controller/UserReviewController.java
  be/tastyhub/src/main/java/com/example/tastyhub/common/domain/userReview/dtos/PagingUserReviewResponse.java
  be/tastyhub/src/main/java/com/example/tastyhub/common/domain/userReview/dtos/UserReviewCreateRequest.java
  be/tastyhub/src/main/java/com/example/tastyhub/common/domain/userReview/dtos/UserReviewUpdateRequest.java
  be/tastyhub/src/main/java/com/example/tastyhub/common/domain/userReview/entity/UserReview.java
  be/tastyhub/src/main/java/com/example/tastyhub/common/domain/userReview/repository/UserReviewRepository.java
  be/tastyhub/src/main/java/com/example/tastyhub/common/domain/userReview/repository/UserReviewRepositoryQuery.java
  be/tastyhub/src/main/java/com/example/tastyhub/common/domain/userReview/repository/UserReviewRepositoryQueryImpl.java
  be/tastyhub/src/main/java/com/example/tastyhub/common/domain/userReview/service/UserReviewService.java
  be/tastyhub/src/main/java/com/example/tastyhub/common/domain/userReview/service/UserReviewServiceImpl.java
  fe/package-lock.json
  fe/package.json
  fe/src/App.js
  fe/src/components/Comment.js
  fe/src/components/CreatePost.js
  fe/src/components/CreateRecipe.js
  fe/src/components/CreateRecipeReview.js
  fe/src/components/CreateUserReview.js
  fe/src/components/DeleteChatroom.js
  fe/src/components/DeletePost.js
  fe/src/components/DeleteRecipe.js
  fe/src/components/DeleteRecipeReview.js
  fe/src/components/DeleteUserReview.js
  fe/src/components/EditPost.js
  fe/src/components/EditRecipe.js
  fe/src/components/EditRecipeReview.js
  fe/src/components/EditUserReview.js
  fe/src/components/Like.js
  fe/src/components/Login.js
  fe/src/components/MainChat.js
  fe/src/components/Post.js
  fe/src/components/PostDetails.js
  fe/src/components/Recipe.js
  fe/src/components/RecipeReview.js
  fe/src/components/Recipedetails.js
  fe/src/components/Scrap.js
  fe/src/components/SendChat.js
  fe/src/components/UserReview.js
  fe/src/components/Village.js
  fe/yarn.lock
Labels: enhancement

#77 fix <(Naver)> : Unauthorization docker container
  be/tastyhub/src/main/java/com/example/tastyhub/common/domain/naver/service/NaverService.java
Labels: bug, fix

#78 feat <(review)> : 레시피 리뷰
  fe/src/App.js
  fe/src/components/CreateRecipe.js
  fe/src/components/CreateRecipeReview.js
  fe/src/components/Like.js
  fe/src/components/MainMypage.js
  fe/src/components/MypageEdit.js
  fe/src/components/MypageShow.js
  fe/src/components/Navbar.js
  fe/src/components/Post.js
  fe/src/components/Recipedetails.js
  fe/src/components/Scrap.js
  fe/src/components/SendChat.js
Labels: enhancement

#81 Chat
  be/tastyhub/src/main/java/com/example/tastyhub/common/domain/chat/dtos/ChatDto.java
  be/tastyhub/src/main/java/com/example/tastyhub/common/domain/chat/entity/Chat.java
  be/tastyhub/src/main/java/com/example/tastyhub/common/domain/chat/service/ChatRoomServiceImpl.java
  be/tastyhub/src/main/java/com/example/tastyhub/common/domain/chat/service/ChatServiceImpl.java
  be/tastyhub/src/main/java/com/example/tastyhub/common/domain/recipe/entity/Recipe.java
  fe/src/App.js
  fe/src/components/Comment.js
  fe/src/components/CreateRecipe.js
  fe/src/components/Login.js
  fe/src/components/MainChat.js
  fe/src/components/Post.js
  fe/src/components/PostDetails.js
  fe/src/components/Recipedetails.js
  fe/src/components/SendChat.js
Labels: fix

#83 feat <(post)> : 게시물 상세조회 기능
  fe/src/App.js
  fe/src/components/Comment.js
  fe/src/components/Post.js
  fe/src/components/PostDetails.js
Labels: enhancement

#82 Mypage
  fe/src/components/MainMypage.js
  fe/src/components/MypageEdit.js
Labels: enhancement

#88 fix <(recipe)> : recipe, foodInformation 연관관계 누락 수정
  be/tastyhub/src/main/java/com/example/tastyhub/common/domain/foodInformation/entity/FoodInformation.java
  be/tastyhub/src/main/java/com/example/tastyhub/common/domain/recipe/entity/Recipe.java
  be/tastyhub/src/main/java/com/example/tastyhub/common/domain/recipe/service/RecipeServiceImpl.java
Labels: bug, fix

#86 Fix recipe
  be/tastyhub/build.gradle
  be/tastyhub/src/main/java/com/example/tastyhub/common/config/SecurityConfig.java
  be/tastyhub/src/main/java/com/example/tastyhub/common/domain/cookstep/entity/CookStep.java
  be/tastyhub/src/main/java/com/example/tastyhub/common/domain/foodInformation/entity/FoodInformation.java
  be/tastyhub/src/main/java/com/example/tastyhub/common/domain/recipe/controller/RecipeController.java
  be/tastyhub/src/main/java/com/example/tastyhub/common/domain/recipe/dtos/RecipeDto.java
  be/tastyhub/src/main/java/com/example/tastyhub/common/domain/recipe/repository/RecipeRepositoryQuery.java
  be/tastyhub/src/main/java/com/example/tastyhub/common/domain/recipe/repository/RecipeRepositoryQueryImpl.java
  be/tastyhub/src/main/java/com/example/tastyhub/common/domain/recipe/service/RecipeService.java
  be/tastyhub/src/main/java/com/example/tastyhub/common/domain/recipe/service/RecipeServiceImpl.java
  be/tastyhub/src/main/java/com/example/tastyhub/common/domain/userReview/controller/UserReviewController.java
  be/tastyhub/src/main/java/com/example/tastyhub/common/utils/Jwt/JwtAuthFilter.java
  be/tastyhub/src/test/java/com/example/tastyhub/common/domain/recipe/controller/RecipeControllerTest.java
  be/tastyhub/src/test/java/com/example/tastyhub/common/domain/recipe/service/RecipeServiceImplTest.java
Labels: enhancement, fix

#87 Like review
  be/tastyhub/src/main/java/com/example/tastyhub/common/config/SecurityConfig.java
  be/tastyhub/src/main/java/com/example/tastyhub/common/domain/like/controller/LikeController.java
  be/tastyhub/src/main/java/com/example/tastyhub/common/domain/like/dtos/LikeCountRequest.java
  be/tastyhub/src/main/java/com/example/tastyhub/common/domain/like/repository/LikeRepository.java
  be/tastyhub/src/main/java/com/example/tastyhub/common/domain/like/service/LikeService.java
  be/tastyhub/src/main/java/com/example/tastyhub/common/domain/like/service/LikeServiceImpl.java
  be/tastyhub/src/main/java/com/example/tastyhub/common/domain/recipeReview/controller/RecipeReviewController.java
  be/tastyhub/src/main/java/com/example/tastyhub/common/domain/recipeReview/dtos/PagingMyRecipeReviewResponse.java
  be/tastyhub/src/main/java/com/example/tastyhub/common/domain/recipeReview/repository/RecipeReviewRepositoryQuery.java
  be/tastyhub/src/main/java/com/example/tastyhub/common/domain/recipeReview/repository/RecipeReviewRepositoryQueryImpl.java
  be/tastyhub/src/main/java/com/example/tastyhub/common/domain/recipeReview/service/RecipeReviewService.java
  be/tastyhub/src/main/java/com/example/tastyhub/common/domain/recipeReview/service/RecipeReviewServiceImpl.java
  be/tastyhub/src/main/java/com/example/tastyhub/common/utils/Jwt/JwtAuthFilter.java
  be/tastyhub/src/test/java/com/example/tastyhub/common/domain/like/service/LikeServiceImplTest.java
  be/tastyhub/src/test/java/com/example/tastyhub/common/domain/recipeReview/service/RecipeReviewServiceImplTest.java
  be/tastyhub/src/test/java/com/example/tastyhub/common/domain/userReview/service/UserReviewServiceImplTest.java
  be/tastyhub/src/test/java/com/example/tastyhub/fixture/like/LikeFixture.java
  be/tastyhub/src/test/java/com/example/tastyhub/fixture/recipeReview/RecipeReviewFixture.java
  be/tastyhub/src/test/java/com/example/tastyhub/fixture/user/UserFixture.java
  be/tastyhub/src/test/java/com/example/tastyhub/fixture/userReview/UserReviewFixture.java
Labels: enhancement, fix

#89 Test code
  be/tastyhub/src/test/java/com/example/tastyhub/common/domain/like/service/LikeServiceImplTest.java
  be/tastyhub/src/test/java/com/example/tastyhub/common/domain/recipe/controller/RecipeControllerTest.java
  be/tastyhub/src/test/java/com/example/tastyhub/common/domain/recipe/service/RecipeServiceImplTest.java
  be/tastyhub/src/test/java/com/example/tastyhub/common/domain/scrap/service/ScrapServiceImplTest.java
  be/tastyhub/src/test/java/com/example/tastyhub/common/domain/user/controller/UserControllerTest.java
  be/tastyhub/src/test/java/com/example/tastyhub/fixture/user/UserFixture.java
Labels: documentation

#93 fix <(dataset)> : dataset 가져오는 과정에서 자잘한 오류나 가져오는 레시피 개수 수정
  data/remakeData.ipynb
Labels: fix

#98 fix <(user)> : user 생성시 이미지 입력 없으면 기본 프로필 이미지로 설정
  be/tastyhub/src/main/java/com/example/tastyhub/common/domain/user/service/UserServiceImpl.java
Labels: fix

#101 fix <(chatting)> : chatting 기능 구현을 위해 로직 수정
  be/tastyhub/src/main/java/com/example/tastyhub/common/domain/chat/controller/ChatRoomController.java
  be/tastyhub/src/main/java/com/example/tastyhub/common/domain/chat/service/ChatRoomServiceImpl.java
  be/tastyhub/src/main/java/com/example/tastyhub/common/domain/userChat/repository/UserChatRoomRepository.java
Labels: fix

#103 Sep037 patch 1
  README.md
Labels: enhancement

#104 fix <(chat)> : 채팅방 상태 확인 로직 변경
  be/tastyhub/src/main/java/com/example/tastyhub/common/domain/chat/controller/ChatRoomController.java
  be/tastyhub/src/main/java/com/example/tastyhub/common/domain/chat/repository/ChatRoomRepository.java
  be/tastyhub/src/main/java/com/example/tastyhub/common/domain/chat/service/ChatRoomService.java
  be/tastyhub/src/main/java/com/example/tastyhub/common/domain/chat/service/ChatRoomServiceImpl.java
Labels: enhancement, fix

#106 fix <(chat)> : roomId 수정
  be/tastyhub/src/main/java/com/example/tastyhub/common/domain/chat/controller/ChatRoomController.java
Labels: fix
