Repository GraduationDku/tastyHub, pull requests merged in 2024-09, with the labels that each got.

#140 Security
  be/tastyhub/src/main/java/com/example/tastyhub/common/config/SecurityConfig.java
  be/tastyhub/src/main/java/com/example/tastyhub/common/domain/user/controller/UserController.java
  be/tastyhub/src/main/java/com/example/tastyhub/common/domain/user/dtos/LoginRequest.java
  be/tastyhub/src/main/java/com/example/tastyhub/common/domain/user/service/UserServiceImpl.java
  be/tastyhub/src/main/java/com/example/tastyhub/common/utils/Jwt/JwtAuthException.java
  be/tastyhub/src/main/java/com/example/tastyhub/common/utils/Jwt/JwtAuthFilter.java
  be/tastyhub/src/main/java/com/example/tastyhub/common/utils/Jwt/JwtService.java
  be/tastyhub/src/test/java/com/example/tastyhub/common/domain/user/controller/UserControllerTest.java
  be/tastyhub/src/test/java/com/example/tastyhub/common/domain/user/service/UserServiceImplTest.java
Labels: enhancement, fix

#141 Front refactory
  fe/src/assets/img/logo.png
  fe/src/components/Chat/MainChat.js
  fe/src/components/HomeScreen.js
  fe/src/components/PageButton.js
  fe/src/components/Post/Post.js
  fe/src/components/Recipe/Recipe.js
  fe/src/components/User/MypageShow.js
  fe/src/index.js
  fe/src/redux/Post/postState.js
  fe/src/store/store.js
Labels: enhancement

#142 Refactory <(pagination)> : 페이지네이션 마무리 작업 및 사용자 검색 오류 수정
  fe/src/App.js
  fe/src/components/Chat/MainChat.js
  fe/src/components/Navbar.js
  fe/src/components/Recipe/Recipe.js
  fe/src/index.js
Labels: enhancement

#146 Wss
  be/tastyhub/build.gradle
  be/tastyhub/src/main/java/com/example/tastyhub/common/config/SecurityConfig.java
  be/tastyhub/src/main/java/com/example/tastyhub/common/domain/chat/controller/ChatRoomController.java
  be/tastyhub/src/main/java/com/example/tastyhub/common/domain/chat/dtos/CheckDto.java
  be/tastyhub/src/main/java/com/example/tastyhub/common/domain/chat/repository/ChatRoomRepository.java
  be/tastyhub/src/main/java/com/example/tastyhub/common/domain/chat/repository/ChatRoomRepositoryQuery.java
  be/tastyhub/src/main/java/com/example/tastyhub/common/domain/chat/repository/ChatRoomRepositoryQueryImpl.java
  be/tastyhub/src/main/java/com/example/tastyhub/common/domain/chat/service/ChatRoomService.java
  be/tastyhub/src/main/java/com/example/tastyhub/common/domain/chat/service/ChatRoomServiceImpl.java
  be/tastyhub/src/main/java/com/example/tastyhub/common/utils/oauth/controller/OAuth2Controller.java
  fe/src/components/Chat/MainChat.js
  fe/src/components/Chat/SendChat.js
  fe/src/components/Post/Post.js
  fe/src/components/Post/PostDetails.js
  fe/src/components/Recipe/Recipe.js
  nginx/nginx.conf
Labels: fix

#147 Refactory <(RefreshToken)> : Redis를 활용한 RefreshToken 시스템 개발
  be/tastyhub/src/main/java/com/example/tastyhub/common/config/SecurityConfig.java
  be/tastyhub/src/main/java/com/example/tastyhub/common/domain/user/controller/UserController.java
  be/tastyhub/src/main/java/com/example/tastyhub/common/domain/user/dtos/UserNameDto.java
  be/tastyhub/src/main/java/com/example/tastyhub/common/domain/user/exception/InvalidTokenException.java
  be/tastyhub/src/main/java/com/example/tastyhub/common/domain/user/service/UserService.java
  be/tastyhub/src/main/java/com/example/tastyhub/common/domain/user/service/UserServiceImpl.java
  be/tastyhub/src/main/java/com/example/tastyhub/common/utils/HttpResponseEntity.java
  be/tastyhub/src/main/java/com/example/tastyhub/common/utils/Jwt/AccessTokenService.java
  be/tastyhub/src/main/java/com/example/tastyhub/common/utils/Jwt/JwtAuthFilter.java
  be/tastyhub/src/main/java/com/example/tastyhub/common/utils/Jwt/JwtService.java
  be/tastyhub/src/main/java/com/example/tastyhub/common/utils/Jwt/RefreshTokenException.java
  be/tastyhub/src/main/java/com/example/tastyhub/common/utils/Jwt/RefreshTokenService.java
  be/tastyhub/src/main/java/com/example/tastyhub/common/utils/Redis/RedisUtil.java
  be/tastyhub/src/main/java/com/example/tastyhub/common/utils/enums/ResponseMessages.java
  be/tastyhub/src/main/java/com/example/tastyhub/common/utils/oauth/service/OAuth2ServiceImpl.java
  be/tastyhub/src/main/java/com/example/tastyhub/common/verified/email/service/EmailServiceImpl.java
  be/tastyhub/src/test/java/com/example/tastyhub/common/domain/user/controller/UserControllerTest.java
  be/tastyhub/src/test/java/com/example/tastyhub/common/domain/user/service/UserServiceImplTest.java
  be/tastyhub/src/test/java/com/example/tastyhub/fixture/user/UserFixture.java
Labels: enhancement
