Repository GraduationDku/tastyHub, pull requests merged in 2024-10, with the labels that each got.

#150 Cache
  be/tastyhub/build.gradle
  be/tastyhub/src/main/java/com/example/tastyhub/TastyhubApplication.java
  be/tastyhub/src/main/java/com/example/tastyhub/common/config/RedisConfig.java
  be/tastyhub/src/main/java/com/example/tastyhub/common/domain/post/controller/PostController.java
  be/tastyhub/src/main/java/com/example/tastyhub/common/domain/post/entity/Post.java
  be/tastyhub/src/main/java/com/example/tastyhub/common/domain/post/repository/PostRepositoryQuery.java
  be/tastyhub/src/main/java/com/example/tastyhub/common/domain/post/repository/PostRepositoryQueryImpl.java
  be/tastyhub/src/main/java/com/example/tastyhub/common/domain/post/service/PostService.java
  be/tastyhub/src/main/java/com/example/tastyhub/common/domain/post/service/PostServiceImpl.java
  be/tastyhub/src/main/java/com/example/tastyhub/common/domain/recipe/controller/RecipeController.java
  be/tastyhub/src/main/java/com/example/tastyhub/common/domain/recipe/repository/RecipeRepositoryQuery.java
  be/tastyhub/src/main/java/com/example/tastyhub/common/domain/recipe/repository/RecipeRepositoryQueryImpl.java
  be/tastyhub/src/main/java/com/example/tastyhub/common/domain/recipe/service/RecipeService.java
  be/tastyhub/src/main/java/com/example/tastyhub/common/domain/recipe/service/RecipeServiceImpl.java
  be/tastyhub/src/main/java/com/example/tastyhub/common/utils/Jwt/AccessTokenService.java
  be/tastyhub/src/main/java/com/example/tastyhub/common/utils/Redis/RedisUtil.java
  be/tastyhub/src/main/java/com/example/tastyhub/common/utils/page/RestPage.java
  be/tastyhub/src/test/java/com/example/tastyhub/fixture/recipe/RecipeFixture.java
  compose.yaml
  redis.conf
Labels: bug, enhancement, fix

#152 Test
  be/tastyhub/src/main/java/com/example/tastyhub/common/utils/Jwt/AccessTokenService.java
  be/tastyhub/src/test/java/com/example/tastyhub/common/domain/post/service/PostServiceImplTest.java
  be/tastyhub/src/test/java/com/example/tastyhub/common/domain/recipe/controller/RecipeControllerTest.java
  be/tastyhub/src/test/java/com/example/tastyhub/common/domain/recipeReview/service/RecipeReviewServiceImplTest.java
  be/tastyhub/src/test/java/com/example/tastyhub/common/domain/user/service/UserServiceImplTest.java
  be/tastyhub/src/test/java/com/example/tastyhub/common/domain/village/service/VillageServiceImplTest.java
  be/tastyhub/src/test/java/com/example/tastyhub/fixture/post/PostFixture.java
  be/tastyhub/src/test/java/com/example/tastyhub/fixture/user/UserFixture.java
  fe/src/components/refreshTokenHandler.js
  fe/src/redux/User/loginState.js
Labels: bug, documentation, enhancement, fix

#153 Test <(Total)> : 오류 테스트 코드 주석처리
  be/tastyhub/src/test/java/com/example/tastyhub/common/domain/comment/controller/CommentControllerTest.java
  be/tastyhub/src/test/java/com/example/tastyhub/common/domain/post/controller/PostControllerTest.java
  be/tastyhub/src/test/java/com/example/tastyhub/common/domain/user/controller/UserControllerTest.java
Labels: bug, fix

#160 Test
  be/tastyhub/src/test/java/com/example/tastyhub/common/domain/comment/controller/CommentControllerTest.java
  be/tastyhub/src/test/java/com/example/tastyhub/common/domain/post/controller/PostControllerTest.java
  be/tastyhub/src/test/java/com/example/tastyhub/common/domain/post/service/PostServiceImplTest.java
  be/tastyhub/src/test/java/com/example/tastyhub/common/domain/recipe/controller/RecipeControllerTest.java
  be/tastyhub/src/test/java/com/example/tastyhub/common/domain/user/controller/UserControllerTest.java
  be/tastyhub/src/test/java/com/example/tastyhub/common/domain/userReview/service/UserReviewServiceImplTest.java
  be/tastyhub/src/test/java/com/example/tastyhub/fixture/post/PostFixture.java
Labels: documentation, fix

#161 Refresh
  fe/src/redux/User/loginState.js
Labels: fix

#162 feature <(accessToken)> : 엑세스 토큰 만료 시간 롤백
  be/tastyhub/src/main/java/com/example/tastyhub/common/utils/Jwt/AccessTokenService.java
Labels: fix

#163 Css
  fe/src/components/Chat/SendChat.js
  fe/src/components/Recipe/Recipe.js
  fe/src/components/Recipe/Recipedetails.js
  fe/src/components/User/Login.js
  fe/src/css/Login.css
  fe/src/css/SendChat.css
Labels: enhancement

#164 Css
  fe/src/App.css
  fe/src/App.js
  fe/src/components/GoogleLoginButton.js
  fe/src/components/User/MainMypage.js
  fe/src/components/User/MypageEdit.js
  fe/src/components/User/MypageShow.js
  fe/src/css/MainMypage.css
  fe/src/css/MypageEdit.css
  fe/src/css/MypageShow.css
Labels: fix
